# Generated by Django 2.0.4 on 2018-04-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('page_h1_text', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=50, primary_key='true', serialize=False)),
            ],
        ),
    ]
