# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_auto_20180420_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('instrument', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='ModelDetail',
        ),
        migrations.DeleteModel(
            name='ModelLinks',
        ),
        migrations.DeleteModel(
            name='ModelModels',
        ),
        migrations.DeleteModel(
            name='ModelPage1',
        ),
        migrations.DeleteModel(
            name='ModelPage2',
        ),
        migrations.DeleteModel(
            name='ModelPage3',
        ),
    ]
