# Generated by Django 2.0.4 on 2018-04-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_auto_20180425_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='page_h1_text',
            new_name='page_text',
        ),
    ]
