# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_auto_20180420_1145'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelDetail',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AlterField(
            model_name='modelpage',
            name='image',
            field=models.ImageField(upload_to=b'templates/images'),
        ),
    ]
