# Generated by Django 2.0.4 on 2018-04-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_auto_20180425_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.CharField(blank=True, max_length=50, primary_key='true', serialize=False),
        ),
    ]
