# Generated by Django 2.0.4 on 2018-04-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_auto_20180425_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='id',
            field=models.CharField(max_length=50, primary_key='true', serialize=False),
        ),
    ]
