# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0005_auto_20180424_0903'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModelPage',
            new_name='Page',
        ),
    ]
