# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 08:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_auto_20180424_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
    ]
