# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0010_remove_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='title',
            field=models.CharField(default=b'Missing', max_length=100),
        ),
    ]
